version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to host.docker.internal:4000/webhook"
    env_file: ./.env
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
     - PORT=$PORT
     - HOST=$HOST
     - DB_HOST=host.docker.internal
     - DB_USER_NAME=$DB_USER_NAME
     - DB_PASSWORD=$DB_PASSWORD
     - DB_NAME=$DB_NAME
     - SEND_MAIL_ACCOUNT=$SEND_MAIL_ACCOUNT
     - SEND_MAIL_PASSWORD=$SEND_MAIL_PASSWORD
     - ENCRYPT_SECRET_KEY=$ENCRYPT_SECRET_KEY
     - JWT_SECRET_KEY=$JWT_SECRET_KEY
     - JWT_REFRESH_SECRET_KEY=$JWT_REFRESH_SECRET_KEY
     - CLOUDINARY_NAME=$CLOUDINARY_NAME
     - CLOUDINARY_KEY=$CLOUDINARY_KEY
     - CLOUDINARY_SECRET=$CLOUDINARY_SECRET
     - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
     - STRIPE_ENDPOINT_SECRET=$STRIPE_ENDPOINT_SECRET
     - NODE_ENV=$NODE_ENV
    stdin_open: true
    tty: true

volumes: 
  db: